apiVersion: v1
kind: Service
metadata:
  name: sea-state-service
  labels:
    app: sea-state-service
    component: exodus-rush
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: sea-state-service
